### ISSUE TITLE
SSLKEYLOGFILE が出力できない

### ISSUE THREAD

**Issue by watahani** [jpdsi/blog#49]
SSLKEYLOGFILE 環境変数後 Edge を再起動するのみでは KeyLog が出力できない。手元の環境ではユーザーを Windows からログオフさせ、環境変数の再読み込みをすることで出力されることを確認しているので、再起動かログオフ & ログインの手順を追加したほうが良さそう。
また、`echo > C:\tmp\ssl.txt` ではなく `echo. > C:\tmp\ssl.txt` で空行を出力するほうが適切に思われる。

---

#### Document Details

⚠ *Do not edit this section.

* ID: f070c304-eddc-5c2e-8810-79e1c06eb634
* 対象記事: [Wireshark による New Microsoft Edge のトレース取得方法](https://jpdsi.github.io/blog/internet-explorer-microsoft-edge/New-Edge-Wireshark/)
* Content Source: [articles/internet-explorer-microsoft-edge/New-Edge-Wireshark.md](https://github.com/jpdsi/blog/blob/main/articles/internet-explorer-microsoft-edge/New-Edge-Wireshark.md)
* Author:

**Comment by georgioush** [comment]
Checking

**Comment by ms-yuhara** [comment]
The issue has been resolved in the following commit.

https://github.com/jpdsi/blog/commit/02434bc731325cfc37843228d8e0b587e352cdae
